import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { LockKeyhole, Mail } from "lucide-react";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";

const schema=z.object({email:z.string().trim().email(),password:z.string().min(6).max(100)});
export const Route=createFileRoute("/auth")({head:()=>({meta:[{title:"Member Sign In | WCBN"},{name:"description",content:"Sign in to WCBN with your existing WCA member credentials."},{property:"og:title",content:"WCBN Member Sign In"},{property:"og:description",content:"Secure access for existing World Changers Association members."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Auth});
function Auth(){const navigate=useNavigate();const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();const valid=schema.safeParse({email,password});if(!valid.success){setError("Enter a valid email and password.");return}setLoading(true);setError("");const {error:authError}=await supabase.auth.signInWithPassword(valid.data);setLoading(false);if(authError){setError("We couldn't sign you in. Check your WCA credentials.");return}navigate({to:"/portal"})}return <main className="grid min-h-screen place-items-center bg-ink px-5 py-12"><div className="w-full max-w-md bg-background p-8 shadow-2xl"><a href="/" className="font-display text-xl font-bold text-primary">WCBN</a><h1 className="mt-10 font-display text-4xl font-bold">Welcome back.</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Use the same email and password you use for your WCA membership.</p><form className="mt-8 space-y-5" onSubmit={submit}><div><Label htmlFor="email">Email address</Label><div className="relative mt-2"><Mail className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} className="h-11 pl-10" autoComplete="email"/></div></div><div><Label htmlFor="password">Password</Label><div className="relative mt-2"><LockKeyhole className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input id="password" type="password" value={password} onChange={e=>setPassword(e.target.value)} className="h-11 pl-10" autoComplete="current-password"/></div></div>{error&&<p className="text-sm text-destructive">{error}</p>}<Button type="submit" size="lg" className="w-full" disabled={loading}>{loading?"Signing in…":"Sign in securely"}</Button></form><p className="mt-6 text-center text-xs text-muted-foreground">No sign-up is needed. WCBN is for existing WCA members.</p></div></main>}