import { createFileRoute, Link } from "@tanstack/react-router";
import { Search, SlidersHorizontal } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { PublicPage } from "@/components/wcbn/public-page";
import { supabase } from "@/integrations/supabase/client";
import type { Database } from "@/integrations/supabase/types";

export const Route=createFileRoute("/businesses")({head:()=>({meta:[{title:"Vetted Business Catalog | WCBN"},{name:"description",content:"Discover trusted businesses led by validated members of the World Changers Business Network."},{property:"og:title",content:"WCBN Business Catalog"},{property:"og:description",content:"Explore vetted enterprises creating ethical and measurable impact."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Businesses});
type Business=Database["public"]["Tables"]["wcbn_businesses"]["Row"];
function Businesses(){const [items,setItems]=useState<Business[]>([]);const [query,setQuery]=useState("");useEffect(()=>{supabase.from("wcbn_businesses").select("*").eq("is_active",true).eq("vetting_status","approved").order("is_featured",{ascending:false}).then(({data})=>setItems(data??[]))},[]);const filtered=useMemo(()=>items.filter(x=>`${x.display_name} ${x.sector} ${x.country}`.toLowerCase().includes(query.toLowerCase())),[items,query]);return <PublicPage eyebrow="Business catalog" title="Trusted enterprises. Meaningful impact." intro="Explore businesses vetted for legitimacy, integrity, excellence and contribution."><section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="flex gap-3"><div className="relative flex-1"><Search className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} className="h-12 pl-11" placeholder="Search businesses, sectors or countries"/></div><Button variant="outline" size="lg"><SlidersHorizontal/> Filters</Button></div>{filtered.length?<div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{filtered.map(x=><Link key={x.id} to="/businesses/$slug" params={{slug:x.slug}} className="group border border-border bg-card"><div className="aspect-[16/9] overflow-hidden bg-secondary">{x.cover_url&&<img src={x.cover_url} alt={`${x.display_name} cover`} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" loading="lazy"/>}</div><div className="p-6"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-gold">{x.sector}</p><h2 className="mt-3 font-display text-2xl font-bold">{x.display_name}</h2><p className="mt-2 text-sm text-muted-foreground">{x.city?`${x.city}, `:""}{x.country}</p><p className="mt-4 line-clamp-3 text-sm leading-6 text-muted-foreground">{x.summary}</p></div></Link>)}</div>:<div className="mt-16 border-y border-border py-20 text-center"><h2 className="font-display text-2xl font-bold">The catalog is being curated.</h2><p className="mt-3 text-muted-foreground">Vetted and activated member businesses will appear here.</p></div>}</section></PublicPage>}
