import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ExternalLink, MapPin } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { PageShell } from "@/components/wcbn/page-shell";
import { supabase } from "@/integrations/supabase/client";
import type { Database } from "@/integrations/supabase/types";
type Business=Database["public"]["Tables"]["wcbn_businesses"]["Row"];
export const Route=createFileRoute("/businesses/$slug")({head:()=>({meta:[{title:"Business Profile | WCBN"},{name:"description",content:"View a vetted WCBN business profile."},{property:"og:title",content:"WCBN Business Profile"},{property:"og:description",content:"A vetted enterprise in the World Changers Business Network."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:BusinessPage});
function BusinessPage(){const {slug}=Route.useParams();const [item,setItem]=useState<Business|null>();useEffect(()=>{supabase.from("wcbn_businesses").select("*").eq("slug",slug).eq("is_active",true).eq("vetting_status","approved").maybeSingle().then(({data})=>setItem(data))},[slug]);if(item===undefined)return <div className="grid min-h-screen place-items-center">Loading business…</div>;if(item===null)return <PageShell><main className="grid min-h-[80vh] place-items-center pt-20"><div className="text-center"><h1 className="font-display text-4xl font-bold">Business not found</h1><Button asChild className="mt-6"><Link to="/businesses">Return to catalog</Link></Button></div></main></PageShell>;return <PageShell><main className="pt-20"><div className="bg-ink"><div className="mx-auto max-w-7xl px-5 py-8 lg:px-8"><Link to="/businesses" className="inline-flex items-center gap-2 text-sm text-primary-foreground/65"><ArrowLeft className="size-4"/>Business catalog</Link><div className="grid items-end gap-8 py-16 md:grid-cols-[1fr_auto]"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-gold">{item.sector}</p><h1 className="mt-4 font-display text-5xl font-bold text-primary-foreground md:text-7xl">{item.display_name}</h1><p className="mt-5 flex items-center gap-2 text-primary-foreground/60"><MapPin className="size-4"/>{item.city?`${item.city}, `:""}{item.country}</p></div>{item.website_url&&<Button asChild size="lg"><a href={item.website_url} target="_blank" rel="noreferrer">Visit website <ExternalLink/></a></Button>}</div></div></div>{item.cover_url&&<img src={item.cover_url} alt={`${item.display_name} business`} className="h-[42vh] w-full object-cover"/>}<section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 md:grid-cols-[2fr_1fr] lg:px-8"><div><h2 className="font-display text-3xl font-bold">About the business</h2><p className="mt-5 whitespace-pre-line leading-8 text-muted-foreground">{item.description||item.summary}</p></div><aside className="border-l border-border pl-6"><p className="text-xs uppercase tracking-[0.12em] text-muted-foreground">WCBN status</p><p className="mt-2 font-semibold text-primary">Vetted and active</p>{item.years_operating&&<><p className="mt-6 text-xs uppercase tracking-[0.12em] text-muted-foreground">Years operating</p><p className="mt-2 font-semibold">{item.years_operating}</p></>}</aside></section></main></PageShell>}