import { createFileRoute } from "@tanstack/react-router";
import { Check, Circle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { PortalShell } from "@/components/wcbn/portal-shell";
export const Route=createFileRoute("/portal/application")({head:()=>({meta:[{title:"Membership Application | WCBN"},{name:"description",content:"Complete the WCBN membership validation application."},{property:"og:title",content:"WCBN Membership Application"},{property:"og:description",content:"Member validation and impact application."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Application});
function Application(){return <PortalShell><h1 className="font-display text-4xl font-bold">Membership application</h1><p className="mt-2 text-muted-foreground">Your existing WCA profile is reused. Only WCBN-specific information is requested.</p><div className="mt-8 grid gap-8 xl:grid-cols-[240px_1fr]"><ol className="space-y-1">{["Eligibility","Character","Business","Leadership","Impact","Review"].map((x,i)=><li className={`flex items-center gap-3 rounded-md px-3 py-3 text-sm ${i===0?"bg-primary text-primary-foreground":"text-muted-foreground"}`} key={x}>{i===0?<Check className="size-4"/>:<Circle className="size-4"/>}{x}</li>)}</ol><form className="border border-border bg-card p-6 md:p-8"><p className="text-xs font-bold uppercase tracking-[0.15em] text-gold">Step 1 of 6</p><h2 className="mt-3 font-display text-3xl font-bold">Confirm your eligibility</h2><p className="mt-2 text-sm text-muted-foreground">These details will be matched to the shared WCA membership records.</p><div className="mt-8 grid gap-5 md:grid-cols-2"><div><Label>WCA membership number</Label><Input className="mt-2" placeholder="Existing member number"/></div><div><Label>DCG</Label><Input className="mt-2" placeholder="Your active DCG"/></div><div className="md:col-span-2"><Label>Why do you want to join WCBN?</Label><Textarea className="mt-2 min-h-32" placeholder="Tell us what you hope to contribute and accomplish"/></div></div><div className="mt-8 flex justify-end"><Button type="button">Save and continue</Button></div></form></div></PortalShell>}
