/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminBusinessesRouteImport } from './routes/admin.businesses'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminContributionsRouteImport } from './routes/admin.contributions'
import { Route as AdminCriteriaRouteImport } from './routes/admin.criteria'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AuthAdminRouteImport } from './routes/auth_.admin'
import { Route as BusinessesSlugRouteImport } from './routes/businesses.$slug'
import { Route as EventsSlugRouteImport } from './routes/events_.$slug'
import { Route as NewsSlugRouteImport } from './routes/news_.$slug'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalApplicationRouteImport } from './routes/portal.application'
import { Route as PortalBusinessRouteImport } from './routes/portal.business'
import { Route as PortalContributionsRouteImport } from './routes/portal.contributions'
import { Route as PortalCovenantRouteImport } from './routes/portal.covenant'
import { Route as PortalEventsRouteImport } from './routes/portal.events'
import { Route as PortalImpactRouteImport } from './routes/portal.impact'
import { Route as PortalNewsRouteImport } from './routes/portal.news'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalEventsSlugRouteImport } from './routes/portal.events.$slug'
import { Route as PortalNewsSlugRouteImport } from './routes/portal.news.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContributionsRoute = AdminContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCriteriaRoute = AdminCriteriaRouteImport.update({
  id: '/criteria',
  path: '/criteria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/auth_/admin',
  path: '/auth/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesSlugRoute = BusinessesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BusinessesRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events_/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news_/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalApplicationRoute = PortalApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBusinessRoute = PortalBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContributionsRoute = PortalContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCovenantRoute = PortalCovenantRouteImport.update({
  id: '/covenant',
  path: '/covenant',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEventsRoute = PortalEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PortalRoute,
} as any)
const PortalImpactRoute = PortalImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNewsRoute = PortalNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEventsSlugRoute = PortalEventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortalEventsRoute,
} as any)
const PortalNewsSlugRoute = PortalNewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortalNewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/impact': typeof ImpactRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/portal': typeof PortalRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contributions': typeof AdminContributionsRoute
  '/admin/criteria': typeof AdminCriteriaRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/admin': typeof AuthAdminRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/portal/application': typeof PortalApplicationRoute
  '/portal/business': typeof PortalBusinessRoute
  '/portal/contributions': typeof PortalContributionsRoute
  '/portal/covenant': typeof PortalCovenantRoute
  '/portal/events': typeof PortalEventsRouteWithChildren
  '/portal/impact': typeof PortalImpactRoute
  '/portal/news': typeof PortalNewsRouteWithChildren
  '/portal/profile': typeof PortalProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/events/$slug': typeof PortalEventsSlugRoute
  '/portal/news/$slug': typeof PortalNewsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/impact': typeof ImpactRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contributions': typeof AdminContributionsRoute
  '/admin/criteria': typeof AdminCriteriaRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/admin': typeof AuthAdminRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/portal/application': typeof PortalApplicationRoute
  '/portal/business': typeof PortalBusinessRoute
  '/portal/contributions': typeof PortalContributionsRoute
  '/portal/covenant': typeof PortalCovenantRoute
  '/portal/events': typeof PortalEventsRouteWithChildren
  '/portal/impact': typeof PortalImpactRoute
  '/portal/news': typeof PortalNewsRouteWithChildren
  '/portal/profile': typeof PortalProfileRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/portal/events/$slug': typeof PortalEventsSlugRoute
  '/portal/news/$slug': typeof PortalNewsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/impact': typeof ImpactRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRoute
  '/portal': typeof PortalRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contributions': typeof AdminContributionsRoute
  '/admin/criteria': typeof AdminCriteriaRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth_/admin': typeof AuthAdminRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/events_/$slug': typeof EventsSlugRoute
  '/news_/$slug': typeof NewsSlugRoute
  '/portal/application': typeof PortalApplicationRoute
  '/portal/business': typeof PortalBusinessRoute
  '/portal/contributions': typeof PortalContributionsRoute
  '/portal/covenant': typeof PortalCovenantRoute
  '/portal/events': typeof PortalEventsRouteWithChildren
  '/portal/impact': typeof PortalImpactRoute
  '/portal/news': typeof PortalNewsRouteWithChildren
  '/portal/profile': typeof PortalProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/events/$slug': typeof PortalEventsSlugRoute
  '/portal/news/$slug': typeof PortalNewsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/businesses'
    | '/contact'
    | '/events'
    | '/impact'
    | '/membership'
    | '/news'
    | '/portal'
    | '/admin/applications'
    | '/admin/businesses'
    | '/admin/categories'
    | '/admin/contributions'
    | '/admin/criteria'
    | '/admin/events'
    | '/admin/members'
    | '/admin/news'
    | '/admin/payments'
    | '/admin/roles'
    | '/admin/settings'
    | '/auth/admin'
    | '/businesses/$slug'
    | '/events/$slug'
    | '/news/$slug'
    | '/portal/application'
    | '/portal/business'
    | '/portal/contributions'
    | '/portal/covenant'
    | '/portal/events'
    | '/portal/impact'
    | '/portal/news'
    | '/portal/profile'
    | '/admin/'
    | '/portal/'
    | '/portal/events/$slug'
    | '/portal/news/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/businesses'
    | '/contact'
    | '/events'
    | '/impact'
    | '/membership'
    | '/news'
    | '/admin/applications'
    | '/admin/businesses'
    | '/admin/categories'
    | '/admin/contributions'
    | '/admin/criteria'
    | '/admin/events'
    | '/admin/members'
    | '/admin/news'
    | '/admin/payments'
    | '/admin/roles'
    | '/admin/settings'
    | '/auth/admin'
    | '/businesses/$slug'
    | '/events/$slug'
    | '/news/$slug'
    | '/portal/application'
    | '/portal/business'
    | '/portal/contributions'
    | '/portal/covenant'
    | '/portal/events'
    | '/portal/impact'
    | '/portal/news'
    | '/portal/profile'
    | '/admin'
    | '/portal'
    | '/portal/events/$slug'
    | '/portal/news/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/businesses'
    | '/contact'
    | '/events'
    | '/impact'
    | '/membership'
    | '/news'
    | '/portal'
    | '/admin/applications'
    | '/admin/businesses'
    | '/admin/categories'
    | '/admin/contributions'
    | '/admin/criteria'
    | '/admin/events'
    | '/admin/members'
    | '/admin/news'
    | '/admin/payments'
    | '/admin/roles'
    | '/admin/settings'
    | '/auth_/admin'
    | '/businesses/$slug'
    | '/events_/$slug'
    | '/news_/$slug'
    | '/portal/application'
    | '/portal/business'
    | '/portal/contributions'
    | '/portal/covenant'
    | '/portal/events'
    | '/portal/impact'
    | '/portal/news'
    | '/portal/profile'
    | '/admin/'
    | '/portal/'
    | '/portal/events/$slug'
    | '/portal/news/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BusinessesRoute: typeof BusinessesRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  ImpactRoute: typeof ImpactRoute
  MembershipRoute: typeof MembershipRoute
  NewsRoute: typeof NewsRoute
  PortalRoute: typeof PortalRouteWithChildren
  AuthAdminRoute: typeof AuthAdminRoute
  EventsSlugRoute: typeof EventsSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/businesses': {
      id: '/admin/businesses'
      path: '/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AdminBusinessesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contributions': {
      id: '/admin/contributions'
      path: '/contributions'
      fullPath: '/admin/contributions'
      preLoaderRoute: typeof AdminContributionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/criteria': {
      id: '/admin/criteria'
      path: '/criteria'
      fullPath: '/admin/criteria'
      preLoaderRoute: typeof AdminCriteriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth_/admin': {
      id: '/auth_/admin'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$slug': {
      id: '/businesses/$slug'
      path: '/$slug'
      fullPath: '/businesses/$slug'
      preLoaderRoute: typeof BusinessesSlugRouteImport
      parentRoute: typeof BusinessesRoute
    }
    '/events_/$slug': {
      id: '/events_/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/$slug': {
      id: '/news_/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/application': {
      id: '/portal/application'
      path: '/application'
      fullPath: '/portal/application'
      preLoaderRoute: typeof PortalApplicationRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/business': {
      id: '/portal/business'
      path: '/business'
      fullPath: '/portal/business'
      preLoaderRoute: typeof PortalBusinessRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/contributions': {
      id: '/portal/contributions'
      path: '/contributions'
      fullPath: '/portal/contributions'
      preLoaderRoute: typeof PortalContributionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/covenant': {
      id: '/portal/covenant'
      path: '/covenant'
      fullPath: '/portal/covenant'
      preLoaderRoute: typeof PortalCovenantRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/events': {
      id: '/portal/events'
      path: '/events'
      fullPath: '/portal/events'
      preLoaderRoute: typeof PortalEventsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/impact': {
      id: '/portal/impact'
      path: '/impact'
      fullPath: '/portal/impact'
      preLoaderRoute: typeof PortalImpactRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/news': {
      id: '/portal/news'
      path: '/news'
      fullPath: '/portal/news'
      preLoaderRoute: typeof PortalNewsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/events/$slug': {
      id: '/portal/events/$slug'
      path: '/$slug'
      fullPath: '/portal/events/$slug'
      preLoaderRoute: typeof PortalEventsSlugRouteImport
      parentRoute: typeof PortalEventsRoute
    }
    '/portal/news/$slug': {
      id: '/portal/news/$slug'
      path: '/$slug'
      fullPath: '/portal/news/$slug'
      preLoaderRoute: typeof PortalNewsSlugRouteImport
      parentRoute: typeof PortalNewsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminBusinessesRoute: typeof AdminBusinessesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContributionsRoute: typeof AdminContributionsRoute
  AdminCriteriaRoute: typeof AdminCriteriaRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminBusinessesRoute: AdminBusinessesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContributionsRoute: AdminContributionsRoute,
  AdminCriteriaRoute: AdminCriteriaRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BusinessesRouteChildren {
  BusinessesSlugRoute: typeof BusinessesSlugRoute
}

const BusinessesRouteChildren: BusinessesRouteChildren = {
  BusinessesSlugRoute: BusinessesSlugRoute,
}

const BusinessesRouteWithChildren = BusinessesRoute._addFileChildren(
  BusinessesRouteChildren,
)

interface PortalEventsRouteChildren {
  PortalEventsSlugRoute: typeof PortalEventsSlugRoute
}

const PortalEventsRouteChildren: PortalEventsRouteChildren = {
  PortalEventsSlugRoute: PortalEventsSlugRoute,
}

const PortalEventsRouteWithChildren = PortalEventsRoute._addFileChildren(
  PortalEventsRouteChildren,
)

interface PortalNewsRouteChildren {
  PortalNewsSlugRoute: typeof PortalNewsSlugRoute
}

const PortalNewsRouteChildren: PortalNewsRouteChildren = {
  PortalNewsSlugRoute: PortalNewsSlugRoute,
}

const PortalNewsRouteWithChildren = PortalNewsRoute._addFileChildren(
  PortalNewsRouteChildren,
)

interface PortalRouteChildren {
  PortalApplicationRoute: typeof PortalApplicationRoute
  PortalBusinessRoute: typeof PortalBusinessRoute
  PortalContributionsRoute: typeof PortalContributionsRoute
  PortalCovenantRoute: typeof PortalCovenantRoute
  PortalEventsRoute: typeof PortalEventsRouteWithChildren
  PortalImpactRoute: typeof PortalImpactRoute
  PortalNewsRoute: typeof PortalNewsRouteWithChildren
  PortalProfileRoute: typeof PortalProfileRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalApplicationRoute: PortalApplicationRoute,
  PortalBusinessRoute: PortalBusinessRoute,
  PortalContributionsRoute: PortalContributionsRoute,
  PortalCovenantRoute: PortalCovenantRoute,
  PortalEventsRoute: PortalEventsRouteWithChildren,
  PortalImpactRoute: PortalImpactRoute,
  PortalNewsRoute: PortalNewsRouteWithChildren,
  PortalProfileRoute: PortalProfileRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BusinessesRoute: BusinessesRouteWithChildren,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  ImpactRoute: ImpactRoute,
  MembershipRoute: MembershipRoute,
  NewsRoute: NewsRoute,
  PortalRoute: PortalRouteWithChildren,
  AuthAdminRoute: AuthAdminRoute,
  EventsSlugRoute: EventsSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
