/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AdminApplicationsRouteImport } from './routes/admin_.applications'
import { Route as AdminBusinessesRouteImport } from './routes/admin_.businesses'
import { Route as AdminContributionsRouteImport } from './routes/admin_.contributions'
import { Route as AdminCriteriaRouteImport } from './routes/admin_.criteria'
import { Route as AdminMembersRouteImport } from './routes/admin_.members'
import { Route as AdminRolesRouteImport } from './routes/admin_.roles'
import { Route as AuthAdminRouteImport } from './routes/auth_.admin'
import { Route as BusinessesSlugRouteImport } from './routes/businesses.$slug'
import { Route as PortalApplicationRouteImport } from './routes/portal_.application'
import { Route as PortalBusinessRouteImport } from './routes/portal_.business'
import { Route as PortalContributionsRouteImport } from './routes/portal_.contributions'
import { Route as PortalCovenantRouteImport } from './routes/portal_.covenant'
import { Route as PortalImpactRouteImport } from './routes/portal_.impact'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin_/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({
  id: '/admin_/businesses',
  path: '/admin/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContributionsRoute = AdminContributionsRouteImport.update({
  id: '/admin_/contributions',
  path: '/admin/contributions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCriteriaRoute = AdminCriteriaRouteImport.update({
  id: '/admin_/criteria',
  path: '/admin/criteria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin_/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin_/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/auth_/admin',
  path: '/auth/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesSlugRoute = BusinessesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BusinessesRoute,
} as any)
const PortalApplicationRoute = PortalApplicationRouteImport.update({
  id: '/portal_/application',
  path: '/portal/application',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalBusinessRoute = PortalBusinessRouteImport.update({
  id: '/portal_/business',
  path: '/portal/business',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalContributionsRoute = PortalContributionsRouteImport.update({
  id: '/portal_/contributions',
  path: '/portal/contributions',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCovenantRoute = PortalCovenantRouteImport.update({
  id: '/portal_/covenant',
  path: '/portal/covenant',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalImpactRoute = PortalImpactRouteImport.update({
  id: '/portal_/impact',
  path: '/portal/impact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/membership': typeof MembershipRoute
  '/portal': typeof PortalRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/contributions': typeof AdminContributionsRoute
  '/admin/criteria': typeof AdminCriteriaRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/roles': typeof AdminRolesRoute
  '/auth/admin': typeof AuthAdminRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/portal/application': typeof PortalApplicationRoute
  '/portal/business': typeof PortalBusinessRoute
  '/portal/contributions': typeof PortalContributionsRoute
  '/portal/covenant': typeof PortalCovenantRoute
  '/portal/impact': typeof PortalImpactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/membership': typeof MembershipRoute
  '/portal': typeof PortalRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/contributions': typeof AdminContributionsRoute
  '/admin/criteria': typeof AdminCriteriaRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/roles': typeof AdminRolesRoute
  '/auth/admin': typeof AuthAdminRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/portal/application': typeof PortalApplicationRoute
  '/portal/business': typeof PortalBusinessRoute
  '/portal/contributions': typeof PortalContributionsRoute
  '/portal/covenant': typeof PortalCovenantRoute
  '/portal/impact': typeof PortalImpactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/businesses': typeof BusinessesRouteWithChildren
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/membership': typeof MembershipRoute
  '/portal': typeof PortalRoute
  '/admin_/applications': typeof AdminApplicationsRoute
  '/admin_/businesses': typeof AdminBusinessesRoute
  '/admin_/contributions': typeof AdminContributionsRoute
  '/admin_/criteria': typeof AdminCriteriaRoute
  '/admin_/members': typeof AdminMembersRoute
  '/admin_/roles': typeof AdminRolesRoute
  '/auth_/admin': typeof AuthAdminRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/portal_/application': typeof PortalApplicationRoute
  '/portal_/business': typeof PortalBusinessRoute
  '/portal_/contributions': typeof PortalContributionsRoute
  '/portal_/covenant': typeof PortalCovenantRoute
  '/portal_/impact': typeof PortalImpactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/businesses'
    | '/contact'
    | '/impact'
    | '/membership'
    | '/portal'
    | '/admin/applications'
    | '/admin/businesses'
    | '/admin/contributions'
    | '/admin/criteria'
    | '/admin/members'
    | '/admin/roles'
    | '/auth/admin'
    | '/businesses/$slug'
    | '/portal/application'
    | '/portal/business'
    | '/portal/contributions'
    | '/portal/covenant'
    | '/portal/impact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/businesses'
    | '/contact'
    | '/impact'
    | '/membership'
    | '/portal'
    | '/admin/applications'
    | '/admin/businesses'
    | '/admin/contributions'
    | '/admin/criteria'
    | '/admin/members'
    | '/admin/roles'
    | '/auth/admin'
    | '/businesses/$slug'
    | '/portal/application'
    | '/portal/business'
    | '/portal/contributions'
    | '/portal/covenant'
    | '/portal/impact'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/businesses'
    | '/contact'
    | '/impact'
    | '/membership'
    | '/portal'
    | '/admin_/applications'
    | '/admin_/businesses'
    | '/admin_/contributions'
    | '/admin_/criteria'
    | '/admin_/members'
    | '/admin_/roles'
    | '/auth_/admin'
    | '/businesses/$slug'
    | '/portal_/application'
    | '/portal_/business'
    | '/portal_/contributions'
    | '/portal_/covenant'
    | '/portal_/impact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BusinessesRoute: typeof BusinessesRouteWithChildren
  ContactRoute: typeof ContactRoute
  ImpactRoute: typeof ImpactRoute
  MembershipRoute: typeof MembershipRoute
  PortalRoute: typeof PortalRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminBusinessesRoute: typeof AdminBusinessesRoute
  AdminContributionsRoute: typeof AdminContributionsRoute
  AdminCriteriaRoute: typeof AdminCriteriaRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AuthAdminRoute: typeof AuthAdminRoute
  PortalApplicationRoute: typeof PortalApplicationRoute
  PortalBusinessRoute: typeof PortalBusinessRoute
  PortalContributionsRoute: typeof PortalContributionsRoute
  PortalCovenantRoute: typeof PortalCovenantRoute
  PortalImpactRoute: typeof PortalImpactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/applications': {
      id: '/admin_/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/businesses': {
      id: '/admin_/businesses'
      path: '/admin/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AdminBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/contributions': {
      id: '/admin_/contributions'
      path: '/admin/contributions'
      fullPath: '/admin/contributions'
      preLoaderRoute: typeof AdminContributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/criteria': {
      id: '/admin_/criteria'
      path: '/admin/criteria'
      fullPath: '/admin/criteria'
      preLoaderRoute: typeof AdminCriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/members': {
      id: '/admin_/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/roles': {
      id: '/admin_/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/admin': {
      id: '/auth_/admin'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$slug': {
      id: '/businesses/$slug'
      path: '/$slug'
      fullPath: '/businesses/$slug'
      preLoaderRoute: typeof BusinessesSlugRouteImport
      parentRoute: typeof BusinessesRoute
    }
    '/portal_/application': {
      id: '/portal_/application'
      path: '/portal/application'
      fullPath: '/portal/application'
      preLoaderRoute: typeof PortalApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal_/business': {
      id: '/portal_/business'
      path: '/portal/business'
      fullPath: '/portal/business'
      preLoaderRoute: typeof PortalBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal_/contributions': {
      id: '/portal_/contributions'
      path: '/portal/contributions'
      fullPath: '/portal/contributions'
      preLoaderRoute: typeof PortalContributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal_/covenant': {
      id: '/portal_/covenant'
      path: '/portal/covenant'
      fullPath: '/portal/covenant'
      preLoaderRoute: typeof PortalCovenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal_/impact': {
      id: '/portal_/impact'
      path: '/portal/impact'
      fullPath: '/portal/impact'
      preLoaderRoute: typeof PortalImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BusinessesRouteChildren {
  BusinessesSlugRoute: typeof BusinessesSlugRoute
}

const BusinessesRouteChildren: BusinessesRouteChildren = {
  BusinessesSlugRoute: BusinessesSlugRoute,
}

const BusinessesRouteWithChildren = BusinessesRoute._addFileChildren(
  BusinessesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BusinessesRoute: BusinessesRouteWithChildren,
  ContactRoute: ContactRoute,
  ImpactRoute: ImpactRoute,
  MembershipRoute: MembershipRoute,
  PortalRoute: PortalRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminBusinessesRoute: AdminBusinessesRoute,
  AdminContributionsRoute: AdminContributionsRoute,
  AdminCriteriaRoute: AdminCriteriaRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminRolesRoute: AdminRolesRoute,
  AuthAdminRoute: AuthAdminRoute,
  PortalApplicationRoute: PortalApplicationRoute,
  PortalBusinessRoute: PortalBusinessRoute,
  PortalContributionsRoute: PortalContributionsRoute,
  PortalCovenantRoute: PortalCovenantRoute,
  PortalImpactRoute: PortalImpactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
